### ISSUE TITLE
Training times

### ISSUE THREAD

**Issue by cellis** [mikakruschel/name-gender-classifier#187]
Hello! I would like to know what loss you trained to? it looks like it's trying to train for 5000 epochs. I added 150000 names or so and I'm training on gpus but it's taking a long time...

**Comment by mikakruschel** [comment]
Hey @cellis, I wrote this a long time ago, so I'm unsure about it. But I definitely had way fewer names (about 1000 or so). Since I'm not planning on maintaining or improving this repo I'm going to archive it.
